import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import { useAuth } from "../context/useAuth.js";

import {getMyAppointmentsRequest, cancelAppointmentRequest} from "../services/Appointment.services.js";

import {formatAppointmentDate, formatAppointmentTime} from "../utils/dateTime.utils.js";

// ============================================================
// MY APPOINTMENTS COMPONENT
// ============================================================

// Displays the appointments associated with the authenticated patient.
const MyAppointments = () => {

  /* Preset Tailwind Styles */

  const loadingClass = "text-sm text-slate-400";
  const errorClass = "mb-4 text-sm text-red-300";
  const emptyClass = "text-sm text-slate-400";
  const listClass = "space-y-4";
  const appointmentCardClass = "rounded-xl border border-slate-700 bg-slate-800 p-4";
  const appointmentGridClass = "grid grid-cols-1 gap-3 md:grid-cols-2";
  const appointmentInfoClass = "text-sm text-slate-300";
  const appointmentLabelClass = "font-medium text-slate-100";
  const statusClass = "text-sm font-medium text-violet-300";
  const reasonClass = "mt-4 text-sm text-slate-300";
  const actionsClass = "mt-5 flex flex-wrap justify-end gap-3 border-t border-slate-700 pt-4";
  const rescheduleButtonClass = "rounded-lg border border-violet-500/40 bg-violet-500/10 px-4 py-2 text-sm font-medium text-violet-300 transition hover:bg-violet-500/20";
  const cancelButtonClass = "rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-2 text-sm font-medium text-red-300 transition hover:bg-red-500/20 disabled:cursor-not-allowed disabled:opacity-50";
  const cancellationFormClass = "mt-4 space-y-3 border-t border-slate-700 pt-4";
  const cancellationTextareaClass = "w-full rounded-lg border border-slate-600 bg-slate-900 px-3 py-2 text-sm text-slate-100 placeholder:text-slate-500 focus:border-violet-500 focus:outline-none"
  const cancellationActionsClass = "flex justify-end gap-3";
  const backButtonClass = "rounded-lg border border-slate-600 px-4 py-2 text-sm text-slate-300 transition hover:bg-slate-700";

  // ============================================================
  // AUTHENTICATION
  // ============================================================

  // Provides access to the authenticated patient and loading state.
  const { user, authLoading } = useAuth();

  // ============================================================
  // NAVIGATION
  // ============================================================

  const navigate = useNavigate();

  // ============================================================
  // APPOINTMENTS STATE
  // ============================================================

  // Stores the authenticated patient's appointments.
  const [appointments, setAppointments] = useState([]);

  // Tracks whether appointments are currently being loaded.
  const [loading, setLoading] = useState(true);

  // Stores errors generated while loading appointments.
  const [error, setError] = useState(null);

  // Stores errors generated by appointment actions.
  const [actionError, setActionError] = useState(null);

  // Stores the appointment currently being processed for cancellation.
  const [cancellingId, setCancellingId] = useState(null);

  // Stores the appointment whose cancellation form is currently visible.
  const [cancellingAppointmentId, setCancellingAppointmentId] =
    useState(null);

  // Stores the cancellation reason entered by the patient.
  const [cancellationReason, setCancellationReason] = useState("");

  // ============================================================
  // LOAD PATIENT APPOINTMENTS
  // ============================================================

  // Loads all appointments associated with the authenticated patient.
  useEffect(() => {

    const loadAppointments = async () => {

      try {

        setLoading(true);
        setError(null);

        const data = await getMyAppointmentsRequest();

        setAppointments(data.appointments || []);

      } catch (error) {

        console.error("Failed to load patient appointments:", error);

        setAppointments([]);

        setError("Failed to load your appointments.");

      } finally {

        setLoading(false);

      }

    };

    if (authLoading) {
      return;
    }

    if (user) {

      loadAppointments();

    } else {

      setAppointments([]);

      setLoading(false);

    }

  }, [user, authLoading]);

  // ============================================================
  // CANCEL APPOINTMENT
  // ============================================================

  // Cancels the selected appointment and updates its local status.
  const handleCancelAppointment = async (appointmentId, cancellationReason) => {

    try {

      setActionError(null);

      setCancellingId(appointmentId);

      await cancelAppointmentRequest(
        appointmentId,
        cancellationReason
      );

      setAppointments((currentAppointments) =>
        currentAppointments.map((appointment) =>
          appointment.id === appointmentId
            ? {
              ...appointment,
              status: "CANCELLED",
            }
            : appointment
        )
      );

      setCancellingAppointmentId(null);

      setCancellationReason("");

    } catch (error) {

      console.error("Failed to cancel appointment:", error);

      setActionError("Unable to cancel the appointment.");

    } finally {

      setCancellingId(null);

    }

  };

  // ============================================================
  // APPOINTMENTS RENDER
  // ============================================================

  return (
    <div>

      {/* Loading state */}
      {loading && (
        <p className={loadingClass}>
          Loading appointments...
        </p>
      )}

      {/* Loading request error */}
      {!loading && error && (
        <p className={errorClass}>
          {error}
        </p>
      )}

      {/* Appointment action error */}
      {!loading && !error && actionError && (
        <p className={errorClass}>
          {actionError}
        </p>
      )}

      {/* Empty state */}
      {!loading && !error && appointments.length === 0 && (
        <p className={emptyClass}>
          You do not have any scheduled appointments.
        </p>
      )}

      {/* Appointments list */}
      {!loading && !error && appointments.length > 0 && (

        <div className={listClass}>

          {appointments.map((appointment) => (

            <article
              key={appointment.id}
              className={appointmentCardClass}>

              <div className={appointmentGridClass}>

                <p className={appointmentInfoClass}>
                  <span className={appointmentLabelClass}>Date:</span>{" "}
                  {formatAppointmentDate(appointment.appointment_date)}
                </p>

                <p className={appointmentInfoClass}>
                  <span className={appointmentLabelClass}>Time:</span>{" "}
                  {formatAppointmentTime(appointment.start_time)}{" "}-{" "}
                  {formatAppointmentTime(appointment.end_time)}
                </p>

                <p className={statusClass}>
                  <span className={appointmentLabelClass}>
                    Status:
                  </span>{" "}
                  {appointment.status}
                </p>

                <p className={appointmentInfoClass}>
                  <span className={appointmentLabelClass}>
                    Specialty:
                  </span>{" "}
                  {appointment.specialty?.name}
                </p>

                <p className={appointmentInfoClass}>
                  <span className={appointmentLabelClass}>
                    Professional:
                  </span>{" "}
                  {appointment.professional?.first_name}{" "}
                  {appointment.professional?.last_name}
                </p>

                <p className={appointmentInfoClass}>
                  <span className={appointmentLabelClass}>
                    Patient:
                  </span>{" "}
                  {appointment.patient?.first_name}{" "}
                  {appointment.patient?.last_name}
                </p>

              </div>

              {/* Appointment reason */}
              {appointment.reason && (

                <p className={reasonClass}>
                  <span className={appointmentLabelClass}>
                    Reason:
                  </span>{" "}
                  {appointment.reason}
                </p>

              )}

              {/* Appointment actions */}
              {appointment.status !== "CANCELLED" && (

                <>

                  <div className={actionsClass}>

                    <button
                      type="button"
                      className={rescheduleButtonClass}
                      onClick={() => navigate(`/appointments/${appointment.id}/reschedule`)}>
                      Reschedule
                    </button>

                    <button
                      type="button"
                      className={cancelButtonClass}
                      onClick={() => {
                        setCancellingAppointmentId(appointment.id);
                        setCancellationReason("");
                        setActionError(null);
                      }}>
                      Cancel Appointment
                    </button>

                  </div>

                  {/* Cancellation reason form */}
                  {cancellingAppointmentId === appointment.id && (

                    <div className={cancellationFormClass}>

                      <textarea
                        value={cancellationReason}
                        onChange={(event) => setCancellationReason(event.target.value)}
                        placeholder="Reason for cancellation"
                        rows="2"
                        className={cancellationTextareaClass} />

                      <div className={cancellationActionsClass}>

                        <button
                          type="button"
                          className={backButtonClass}
                          onClick={() => {
                            setCancellingAppointmentId(null);
                            setCancellationReason("");
                            setActionError(null);
                          }} >
                          Back
                        </button>

                        <button
                          type="button"
                          className={cancelButtonClass}
                          disabled={
                            cancellingId === appointment.id ||
                            !cancellationReason.trim()
                          }
                          onClick={() =>
                            handleCancelAppointment(
                              appointment.id,
                              cancellationReason.trim()
                            )}>
                          {cancellingId === appointment.id
                            ? "Cancelling..."
                            : "Confirm Cancellation"}
                        </button>

                      </div>

                    </div>

                  )}

                </>

              )}

            </article>

          ))}

        </div>

      )}

    </div>
  );
};

export default MyAppointments;